In [1]:
import numpy as np # linear algebra
import pandas as pd

In [2]:
df=pd.read_csv(r'E:\1biplav\data\Dataset\heart dibities\Heart.csv')

In [3]:
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [4]:
df.shape

(303, 15)

In [5]:
df['Thal'].value_counts()

normal        166
reversable    117
fixed          18
Name: Thal, dtype: int64

In [6]:
df['ChestPain'].value_counts()

asymptomatic    144
nonanginal       86
nontypical       50
typical          23
Name: ChestPain, dtype: int64

In [7]:
df['AHD'].value_counts()

No     164
Yes    139
Name: AHD, dtype: int64

In [8]:
df['Ca'].value_counts()

0.0    176
1.0     65
2.0     38
3.0     20
Name: Ca, dtype: int64

In [9]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import  OneHotEncoder,OrdinalEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

In [82]:
## adding simple imputer to Ca   and Thal col
si=SimpleImputer(strategy="most_frequent")
Ca1=si.fit_transform(df[['Ca']])

In [83]:
Ca1

array([[0.],
       [3.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],

In [85]:
ca2=pd.DataFrame(Ca1,columns=['Ca'])

In [25]:
si=SimpleImputer(strategy="most_frequent")
thal_new=si.fit_transform(df[['Thal']])

In [32]:
pd.DataFrame(thal_new,columns=['Thal'])

Thal
0         fixed
1        normal
2    reversable
3        normal
4        normal
..          ...
298  reversable
299  reversable
300  reversable
301      normal
302      normal

[303 rows x 1 columns]

In [35]:
# Ordinalencoding -> ChestPain and Thal
oe=OrdinalEncoder(categories=[['asymptomatic','nonanginal','nontypical','typical']])
CheasPain_new=oe.fit_transform(df[['ChestPain']])
CheasPain_new


array([[3.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [3.],
       [3.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [3.],
       [0.],
       [0.],
       [3.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [3.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [43]:
CheasPain2=pd.DataFrame(CheasPain_new,columns=['cheast'])


In [46]:
CheasPain2

cheast
0       3.0
1       0.0
2       0.0
3       1.0
4       2.0
..      ...
298     3.0
299     0.0
300     0.0
301     2.0
302     1.0

[303 rows x 1 columns]

In [58]:
oe=OrdinalEncoder(categories=[['normal','reversable','fixed']])
thal2=oe.fit_transform(thal_new,[['Thal']])
thal2


array([[2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],

In [66]:
thal1=pd.DataFrame(thal2,columns=['thal'])
thal1

thal
0     2.0
1     0.0
2     1.0
3     0.0
4     0.0
..    ...
298   1.0
299   1.0
300   1.0
301   0.0
302   0.0

[303 rows x 1 columns]

In [53]:
#lable encoding
lr=LabelEncoder()
AHD=lr.fit_transform(df['AHD'])

In [56]:
AHD_new=pd.DataFrame(AHD,columns=['AHD'])
AHD_new

AHD
0      0
1      1
2      1
3      0
4      0
..   ...
298    1
299    1
300    1
301    1
302    0

[303 rows x 1 columns]

In [60]:
X=df.drop(['ChestPain','Thal','AHD','Ca'],axis=1)

In [61]:
X

Unnamed: 0  Age  Sex  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0             1   63    1     145   233    1        2    150      0      2.3   
1             2   67    1     160   286    0        2    108      1      1.5   
2             3   67    1     120   229    0        2    129      1      2.6   
3             4   37    1     130   250    0        0    187      0      3.5   
4             5   41    0     130   204    0        2    172      0      1.4   
..          ...  ...  ...     ...   ...  ...      ...    ...    ...      ...   
298         299   45    1     110   264    0        0    132      0      1.2   
299         300   68    1     144   193    1        0    141      0      3.4   
300         301   57    1     130   131    0        0    115      1      1.2   
301         302   57    0     130   236    0        2    174      0      0.0   
302         303   38    1     138   175    0        0    173      0      0.0   

     Slope  
0        3  
1        2  
2        2  
3        3  
4        1  
..     ...  
298      2  
299      2  
300      2  
301      2  
302      1  

[303 rows x 11 columns]

In [86]:
df_new=pd.concat([X,AHD_new,thal1,CheasPain2,ca2],axis=1)

In [87]:
df_new.shape

(303, 15)

In [88]:
df.shape

(303, 15)

In [90]:
df_new.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
AHD           0
thal          0
cheast        0
Ca            0
dtype: int64

In [91]:
df_new.head()

Unnamed: 0  Age  Sex  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0           1   63    1     145   233    1        2    150      0      2.3   
1           2   67    1     160   286    0        2    108      1      1.5   
2           3   67    1     120   229    0        2    129      1      2.6   
3           4   37    1     130   250    0        0    187      0      3.5   
4           5   41    0     130   204    0        2    172      0      1.4   

   Slope  AHD  thal  cheast   Ca  
0      3    0   2.0     3.0  0.0  
1      2    1   0.0     0.0  3.0  
2      2    1   1.0     0.0  2.0  
3      3    0   0.0     1.0  0.0  
4      1    0   0.0     2.0  0.0

In [93]:
df2=df_new.copy()

In [105]:
X=df2.drop('AHD',axis=1)
y=df['AHD']
print('shape of X=',X.shape)
print('shape of y=',y.shape)

shape of X= (303, 14)
shape of y= (303,)


In [107]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2)
print('shape of X_train=',X_train.shape)
print('shape of X_test=',X_test.shape)
print('shape of y_train=',y_train.shape)
print('shape of y_test=',y_test.shape)

shape of X_train= (242, 14)
shape of X_test= (61, 14)
shape of y_train= (242,)
shape of y_test= (61,)


In [108]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [109]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [110]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\VPO17\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [112]:
y_pre1=clf1.predict(X_test)
y_pre2=clf2.predict(X_test)

In [116]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pre1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pre2))

Accuracy of Logistic Regression 0.7704918032786885
Accuracy of Decision Trees 0.6557377049180327


In [117]:
confusion_matrix(y_test,y_pre1)

array([[22,  7],
       [ 7, 25]], dtype=int64)

In [118]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pre1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  22   7
1   7  25

In [119]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pre2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  19  10
1  11  21

In [121]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pre1
result['Decision Tree Prediction'] = y_pre1

In [124]:
result.sample(10)

Actual Label Logistic Regression Prediction Decision Tree Prediction
116           No                             No                       No
282          Yes                            Yes                      Yes
232          Yes                            Yes                      Yes
238           No                             No                       No
223          Yes                            Yes                      Yes
69           Yes                             No                       No
233           No                             No                       No
137          Yes                            Yes                      Yes
246          Yes                            Yes                      Yes
213          Yes                            Yes                      Yes

In [128]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [146]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pre1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Recall - ",recall_score(y_test,y_pre1,average='binary',pos_label='Yes'))
print("F1 score - ",f1_score(y_test,y_pre1,pos_label='Yes'))
print("Precision - ",precision_score(y_test,y_pre1,pos_label='Yes'))

For Logistic regression Model
--------------------------------------------------
    0   1
0  22   7
1   7  25
--------------------------------------------------
Recall -  0.78125
F1 score -  0.78125
Precision -  0.78125


In [152]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pre2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pre2,pos_label='Yes'))
print("Recall - ",recall_score(y_test,y_pre2,pos_label='Yes'))
print("F1 score - ",f1_score(y_test,y_pre2,pos_label='Yes'))

For DT Model
--------------------------------------------------
    0   1
0  19  10
1  11  21
--------------------------------------------------
Precision -  0.6774193548387096
Recall -  0.65625
F1 score -  0.6666666666666667


In [153]:
precision_score(y_test,y_pre1,average=None)

array([0.75862069, 0.78125   ])

In [154]:
precision_score(y_test,y_pre2,average=None)

array([0.63333333, 0.67741935])

In [155]:
recall_score(y_test,y_pre2,average=None)

array([0.65517241, 0.65625   ])