In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np



In [6]:
""" already apply non value .all variable are  numerical so  already data prepaire for apply linear regression"""
df=pd.read_csv(r"E:\1biplav\data\Dataset\bangalore house price prediction_Linear regression\bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0     3      2.0  150.0          1672.0    3     8971.291866   
1     3      3.0  149.0          1750.0    3     8514.285714   
2     3      2.0  150.0          1750.0    3     8571.428571   
3     2      2.0   40.0          1250.0    2     3200.000000   
4     2      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

# Split Data

In [11]:
#price= indepemdeny variablr 
X=df.drop('price',axis=1)
y=df['price']
print('shape of X=',X.shape)
print('shape of y=',y.shape)

shape of X= (7120, 107)
shape of y= (7120,)


In [15]:
#should be between 0.0 and 1.0 and represent the proportion of the dataset to include in the test split
#(80% data fortrain and 20% for test) )
from sklearn.model_selection import train_test_split   
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=51)
print('shape of X_train=',X_train.shape)
print('shape of X_test=',X_test.shape)
print('shape of y_train=',y_train.shape)
print('shape of y_test=',y_test.shape)

shape of X_train= (5696, 107)
shape of X_test= (1424, 107)
shape of y_train= (5696,)
shape of y_test= (1424,)


# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 3.0245515 ,  0.55008644,  1.33396246, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 , -0.60737352, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.36873754, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-0.44274597,  0.55008644, -0.49772996, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.62414253, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.6009239 , ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [22]:
X_test

array([[ 3.00000000e+00,  1.58437574e+00,  1.70000000e+03, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17],
       [ 2.00000000e+00,  2.00000000e+00,  1.01600000e+03, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17],
       [ 4.00000000e+00,  2.00000000e+00,  1.95000000e+03, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17],
       ...,
       [ 1.00000000e+00,  2.00000000e+00,  6.65000000e+02, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17],
       [ 2.00000000e+00,  1.00000000e+00,  1.16700000e+03, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17],
       [ 2.00000000e+00, -8.48260288e-17,  1.56600000e+03, ...,
         3.74232480e-18, -1.06032536e-17, -2.49488320e-17]])

# Linear Regression - ML Model Training

In [34]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [35]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468907e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029427e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968546e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886277e-01,  8.03443207e-01,  2.99182164e+00,  3.86430422e-03,
        1.05037260e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [36]:
lr.intercept_

95.08027299859552

# Predict the value of Home and Test

In [58]:
X_test[0, :]

array([ 3.00000000e+00,  1.58437574e+00,  1.70000000e+03,  3.00000000e+00,
        4.70588235e+03,  6.76737068e-17,  1.00000000e+00, -4.61553392e-17,
        1.00000000e+00,  7.54702168e-17, -1.96472052e-17,  3.18097608e-17,
       -1.99590656e-17, -4.98976640e-18, -1.49692992e-17, -9.97953281e-18,
       -2.46369716e-17,  3.24334816e-17, -1.74641824e-17,  4.67790600e-19,
       -5.61348720e-18,  1.12269744e-17,  7.98362624e-17, -4.61553392e-17,
        4.98976640e-18, -1.24744160e-18,  8.73209120e-18,  4.98976640e-17,
       -2.61962736e-17,  4.36604560e-17, -3.67995272e-17, -3.74232480e-18,
       -8.73209120e-18,  3.74232480e-18,  6.23720800e-19, -2.24539488e-17,
       -4.98976640e-18,  2.93148776e-17,  9.97953281e-18, -6.86092880e-18,
       -2.74437152e-17, -1.99590656e-17, -1.24744160e-17,  3.49283648e-17,
        0.00000000e+00,  2.61962736e-17, -1.77760428e-17, -3.74232480e-18,
       -4.05418520e-18, -1.87116240e-18, -1.24744160e-18,  4.74027808e-17,
       -2.49488320e-17,  

In [54]:
lr.predict([X_test[0, :]]) # predict 0  means 1  house information  and  all columns

array([411576.77540755])

In [55]:
lr.predict(X_test)  #predict all information

array([411576.77540755, 310746.97778616, 515608.73130917, ...,
       332099.2019245 , 407373.5113308 , 791290.97974434])

In [56]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [49]:
lr.score(X_test, y_test)

-13283418.33900294

In [59]:
"going something wrong"

'going something wrong'